on: 
  [workflow_dispatch]

name: azureClusterCreation
jobs:
  buildCluster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Get author name
      id: author
      run: echo "::set-output name=author::$(git show -s --format=%an)"
    - name: Print author name
      run: echo "${{ steps.author.outputs.author }}"
    - name: Print author name with an environment variable
      run: echo $AUTHOR_NAME
      env:
          AUTHOR_NAME: ${{ steps.author.outputs.author }}    
      





#     - name: create ACR
#         PublicIP:${{ az network public-ip create --resource-group cluster-rg-dev-nrg --name PublicIpForIngress --sku Standard --allocation-method static --query publicIp.ipAddress -o tsv }}
#       run: 
# #          az group create --name bradlab-acr-rg --location australiasoutheast
#           az aks get-credentials --resource-group cluster-rg-dev --name cluster-rg-dev-cluster --overwrite-existing
# #          az network public-ip create --resource-group cluster-rg-dev-nrg --name PublicIpForIngress --sku Standard --allocation-method static --query publicIp.ipAddress -o tsv
#     - name: Get author name
#       id: author
#       run: echo "::set-output name=author::$(az network public-ip create --resource-group cluster-rg-dev-nrg --name PublicIpForIngress --sku Standard --allocation-method static --query publicIp.ipAddress -o tsv)"             
#     - name : print author
#       run: echo ${{ steps.author.outputs.author }}
   
 
#     - name: Terraform Install
#       env:
#         TERRAFORM_VERSION: "1.1.0"
#       run: |
#           tf_version=$TERRAFORM_VERSION
#           wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
#           unzip terraform_"$tf_version"_linux_amd64.zip
#           sudo mv terraform /usr/local/bin/
          
#     - name: Terraform version
#       run: terraform --version
        
#     - name: Terraform Init
#       run: terraform init
# #      run: |
# #        az login
# #        terraform init -input=false
# #        terraform plan
# #        terraform apply -auto-approve -input=false
