on: 
  [workflow_dispatch]

name: azureClusterCreation
jobs:
  buildCluster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    
    - name: create ACR
      run: 
#          az group create --name bradlab-acr-rg --location australiasoutheast
          az aks get-credentials --resource-group cluster-rg-dev --name cluster-rg-dev-cluster --overwrite-existing
   
#     - name: Terraform Install
#       env:
#         TERRAFORM_VERSION: "1.1.0"
#       run: |
#           tf_version=$TERRAFORM_VERSION
#           wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
#           unzip terraform_"$tf_version"_linux_amd64.zip
#           sudo mv terraform /usr/local/bin/
          
#     - name: Terraform version
#       run: terraform --version
        
#     - name: Terraform Init
#       run: terraform init
# #      run: |
# #        az login
# #        terraform init -input=false
# #        terraform plan
# #        terraform apply -auto-approve -input=false
